# _quarto.yml

project:
  type: book
  output-dir: docs

book:
  title: "The AI Jungle"
  subtitle: "Learn AI & ML with Nature's Wisdom"
  author: "Amit Verma"
  date: "2025-07-18"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - chapter6.qmd
    - chapter_timeseries.qmd
    - chapter7.qmd
    - chapter8.qmd
    - chapter9.qmd
    - chapter10.qmd
    - chapter11.qmd
    - chapter12.qmd
    - chapter13.qmd
    - chapter14.qmd
    - chapter15.qmd
    - chapter16.qmd
    - chapter17.qmd
    - chapter18.qmd
    - chapter19.qmd


website:
  title: "The AI Jungle"
  repo-url: https://github.com/akv004/the-ai-jungle
  repo-actions: [edit, issue]
  site-url: https://akv004.github.io/the-ai-jungle/
  twitter-card: true
  reader-mode: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Intro"
        href: intro.qmd
      - text: "Chapter 1"
        href: chapter1.qmd
      - text: "Chapter 2"
        href: chapter2.qmd
      - text: "Chapter 3"
        href: chapter3.qmd
      - text: "Chapter 4"
        href: chapter4.qmd
      - text: "Chapter 5"
        href: chapter5.qmd
      - text: "Chapter 6"
        href: chapter6.qmd
      - text: "Forecasting"
        href: chapter_timeseries.qmd
      - text: "Chapter 7"
        href: chapter7.qmd
      - text: "Chapter 8"
        href: chapter8.qmd
      - text: "Chapter 9"
        href: chapter9.qmd
      - text: "Chapter 10"
        href: chapter10.qmd
      - text: "Chapter 11"
        href: chapter11.qmd
      - text: "Chapter 12"
        href: chapter12.qmd
      - text: "Chapter 13"
        href: chapter13.qmd
      - text: "Chapter 14"
        href: chapter14.qmd
      - text: "Chapter 15"
        href: chapter15.qmd
      - text: "Chapter 16"
        href: chapter16.qmd
      - text: "Chapter 17"
        href: chapter17.qmd
      - text: "Chapter 18"
        href: chapter18.qmd
      - text: "Chapter 19"
        href: chapter19.qmd
    right:
      - text: "☕ Support"
        href: https://ko-fi.com/amitverma27904


format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    number-sections: false
    self-contained: false
    grid:
      body-width: 1050px
      sidebar-width: 250px
      margin-width: 150px
