# _quarto-alt.yml

project:
  type: book
  output-dir: docs

book:
  title: "The AI Jungle"
  subtitle: "Learn AI & ML with Nature's Wisdom"
  author: "Amit Verma"
  date: "2025-07-18"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - chapter6.qmd
    - chapter_timeseries.qmd
    - chapter7.qmd
    - chapter8.qmd
    - chapter9.qmd
    - chapter10.qmd
    - chapter11.qmd
    - chapter12.qmd
    - chapter13.qmd
    - chapter14.qmd
    - chapter15.qmd
    - chapter16.qmd
    - chapter17.qmd
    - chapter18.qmd
    - chapter19.qmd


website:
  title: "The AI Jungle"
  repo-url: https://github.com/amitverma/TheQuantumMirror
  repo-actions: [edit, issue]
  site-url: https://amitverma.github.io/TheQuantumMirror/
  twitter-card: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Intro"
        href: intro.qmd
      - text: "chapter1"
        href: chapter1.qmd
      - text: "chapter2"
        href: chapter2.qmd
      - text: "chapter3"
        href: chapter3.qmd
      - text: "chapter4"
        href: chapter4.qmd
      - text: "chapter5"
        href: chapter5.qmd
      - text: "chapter6"
        href: chapter6.qmd
      - text: "forecasting"
        href: chapter_timeseries.qmd
      - text: "chapter7"
        href: chapter7.qmd
      - text: "chapter8"
        href: chapter8.qmd
      - text: "chapter9"
        href: chapter9.qmd
      - text: "chapter10"
        href: chapter10.qmd
      - text: "chapter11"
        href: chapter11.qmd
      - text: "chapter12"
        href: chapter12.qmd
      - text: "chapter13"
        href: chapter13.qmd
      - text: "chapter14"
        href: chapter14.qmd
      - text: "chapter15"
        href: chapter15.qmd
      - text: "chapter16"
        href: chapter16.qmd
      - text: "chapter17"
        href: chapter17.qmd
      - text: "chapter18"
        href: chapter18.qmd
      - text: "chapter19"
        href: chapter19.qmd
    right:
      - text: "☕ Support"
        href: https://ko-fi.com/amitverma27904


format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    number-sections: false
    self-contained: false


