name: Quarto Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install LaTeX for PDF rendering
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex \
            texlive-fonts-recommended \
            texlive-plain-generic \
            texlive-latex-recommended \
            texlive-latex-extra \
            fonts-freefont-ttf

      - name: Render Quarto project (HTML, PDF, EPUB)
        run: |
          quarto render

      - name: Upload website (docs/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
